bones
ericbfriday/MusicNerdz pull request #6
Opened 2017-11-04 23:23 UTC by aurorahager

Very rough module view for students with hard coded data.
only looks okay on ipad view currently.
added ng-youtube-embed to vendors.

2017-11-05 17:11 UTC, ericbfriday submitted a review, later dismissed
We have a lot of /demo bloat in the vendors file that is unneeded. Below are some removes and notes. 
Remove ng-youtube-embed/README.md
Remove ng-youtube-embed/demo/app.js
Remove ng-youtube-embed/demo/index.html
Remove ng-youtube-embed/demo/styles.css
Remove /ng-youtube-embed/icon.png
/views/templates/lesson.html -> Do a song with less explicit lyrics. Let’s keep our GitHub repo school appropriate.

2017-11-05 19:54 UTC, mikeekert commented on server/public/styles/style.css
> +.sizeMd {
Can we swap the pixel sizes to rem's (this allows us to adjust the entire site's font sizes universally if we want to scale them up/down all together).

2017-11-06 19:28 UTC, carlabrady submitted a review, later dismissed
looks good

2017-11-06 21:04 UTC, ericbfriday requested changes

2017-11-06 21:04 UTC, ericbfriday commented on server/public/views/index.html
> +        <script src="vendors/angular-jk/jk-carousel.js"></script>
Sourcing carousel twice. Remove one.

2017-11-06 21:04 UTC, ericbfriday commented on server/public/views/index.html
> +        <script src="vendors/ng-youtube-embed/build/ng-youtube-embed.min.js"></script>
Sourcing youtube-embed twice. Remove one.

2017-11-06 21:06 UTC, ericbfriday approved these changes
Second Level Review Approved. Merging.

2017-11-06 21:07 UTC, merged